# Synaps Docker Compose File
# By: Ian P
# This version of Docker Compose file is designed to work with the Synaps project.
# It includes services for Laravel, Redis, MariaDB, phpMyAdmin, and a Redis WebSocket bridge.

version: '3.8'

services:

  # --------------------------------- LARAVEL --------------------------------- #
  synaps-back:
    build:
      context: ./Synaps-back/laravel
      dockerfile: Dockerfile
    container_name: synaps-back
    ports:
      - "8010:80" # Laravel en Apache
    volumes:
      - ./Synaps-back/laravel/app:/var/www/html/app
      - ./Synaps-back/laravel/routes:/var/www/html/routes
      - ./Synaps-back/laravel/resources:/var/www/html/resources
      - ./Synaps-back/laravel/public:/var/www/html/public
      - ./Synaps-back/laravel/.env.example:/var/www/html/.env
    depends_on:
      - synaps-mariadb
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8010
      DB_CONNECTION: mysql
      DB_HOST: synaps-mariadb
      DB_PORT: "3307"
      DB_DATABASE: synaps
      DB_USERNAME: root
      DB_PASSWORD: root
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"

  # --------------------------------- REDIS --------------------------------- #
  synaps-redis:
    image: redis:latest
    container_name: synaps-redis
    ports:
      - "6380:6379"
    volumes:
      - synaps_redis_data:/data

  # --------------------------------- REDIS-BRIDGE --------------------------------- #
  redis-ws-bridge:
    image: node:18
    container_name: synaps-redis-ws-bridge
    working_dir: /app
    volumes:
      - ./redis-ws-bridge:/app
    command: ["npm", "start"]
    depends_on:
      - synaps-redis
    environment:
      - REDIS_URL=redis://synaps-redis:6379
      - WS_PORT=8084

  # --------------------------------- MARIADB --------------------------------- #
  synaps-mariadb:
    image: mariadb:latest
    container_name: synaps-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=synaps
    ports:
      - "3307:3306"
    volumes:
      - synaps_mariadb_data:/var/lib/mysql

  # --------------------------------- PHPMYADMIN --------------------------------- #
  synaps-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: synaps-phpmyadmin
    environment:
      - PMA_HOST=synaps-mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8083:80"
    depends_on:
      - synaps-mariadb

volumes:
  synaps_mariadb_data:
  synaps_redis_data: