# Synaps Docker Compose File
# By: Ian P
# This version of Docker Compose file is designed to work with the Synaps project.
# It includes services for Laravel, Redis, MariaDB, phpMyAdmin, and a Redis WebSocket bridge.

version: '3.8'

services:

  # --------------------------------- LARAVEL --------------------------------- #
  synaps-back:
    build:
      context: ./Synaps-back/laravel
      dockerfile: Dockerfile
    container_name: synaps-back
    ports:
      - "8010:80" # Laravel en Apache
    volumes:
      # - ./Synaps-back/laravel:/var/www/html   # Eliminado
      - ./SQL:/var/www/html/SQL
      - ./Synaps-back/laravel/app:/var/www/html/app
      - ./Synaps-back/laravel/routes:/var/www/html/routes
      - ./Synaps-back/laravel/resources:/var/www/html/resources
      - ./Synaps-back/laravel/public:/var/www/html/public
      - /c/Users:/windows-users:rw  
    env_file:
      - ./Synaps-back/laravel/.env
    # El script docker-entrypoint.sh se encarga de la configuración inicial

    depends_on:
      - synaps-mariadb
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8010
      DB_CONNECTION: mysql
      DB_HOST: synaps-mariadb
      DB_PORT: "3306"
      DB_DATABASE: synaps
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "0"
      USERNAME: ${USERNAME}

  # --------------------------------- REDIS --------------------------------- #
  synaps-redis:
    image: redis:latest
    container_name: synaps-redis
    ports:
      - "6380:6379"
    volumes:
      - synaps_redis_data:/data

  # --------------------------------- REDIS-BRIDGE --------------------------------- #
  redis-ws-bridge:
    image: node:18
    container_name: synaps-redis-ws-bridge
    working_dir: /app
    volumes:
      - ./redis-ws-bridge:/app
    command: ["npm", "start"]
    depends_on:
      - synaps-redis
    environment:
      - REDIS_URL=redis://synaps-redis:6379
      - WS_PORT=8084
    ports:
      - "8084:8084"   

  # --------------------------------- MARIADB --------------------------------- #
  synaps-mariadb:
    image: mariadb:latest
    container_name: synaps-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=synaps
    ports:
      - "3307:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --------------------------------- PHPMYADMIN --------------------------------- #
  synaps-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: synaps-phpmyadmin
    environment:
      - PMA_HOST=synaps-mariadb
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    ports:
      - "8083:80"
    depends_on:
      - synaps-mariadb

  # --------------------------------- KEYCLOAK --------------------------------- #
  synaps-keycloak:
    image: quay.io/keycloak/keycloak:23.0.0 
    container_name: synaps-keycloak
    ports:
      - "8085:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --features=preview,admin-fine-grained-authz
    depends_on:
      - synaps-mariadb
    volumes:
      - synaps_keycloak_data:/opt/keycloak/data

  # --------------------------------- IDP-FLASK --------------------------------- #
  synaps-idp-flask:
    build:
      context: ./synaps-idp-flask
    ports:
      - "5005:5005"
    env_file:
      - ./synaps-idp-flask/.env
    depends_on:
      - synaps-mariadb

volumes:
  synaps_mariadb_data:
  synaps_redis_data:
  synaps_keycloak_data:
