FROM php:8.2-apache

# Instalar herramientas básicas y dependencias PHP
RUN apt-get update && apt-get install -y \
    git curl zip unzip nano bash \
    libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Establecer directorio de trabajo
WORKDIR /var/www

# Copiar primero composer config para instalar dependencias
COPY composer.json composer.lock /var/www/

# Instalar dependencias de producción + firebase/php-jwt
RUN composer install --no-dev --no-interaction && composer require firebase/php-jwt

# Copiar el resto del proyecto
COPY . /var/www/

# Crear carpetas necesarias y asegurar permisos correctos
RUN mkdir -p /var/www/storage /var/www/bootstrap/cache \
    && chown -R www-data:www-data /var/www \
    && chmod -R 775 /var/www/storage /var/www/bootstrap/cache
